### ISSUE TITLE
Some events give an error while retrieving albums

### ISSUE THREAD

**Issue by jonathanjuursema** [kickin-media/media-back-end#150]
For example:

```bash
➜  ~ curl https://api.kick-in.media/event/9cc205de-780b-4c60-aa38-d6196fed77b5/albums
Internal Server Error
```

This seems to be an issue with some data structuring in the API. These are the error logs:

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
 ...
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 315, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 155, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 1 validation errors:
  {'loc': ('response', 16, 'cover_photo', 'timestamp'), 'msg': 'invalid datetime format', 'type': 'value_error.datetime'}
```

I've checked the database, none of the albums in the event have a cover photo and so should default to the first one. I don't yet know what the exact issue is.

**Comment by jonathanjuursema** [comment]
This issue has been fixed!

Apparently, there were some archived and imported photos (from before this website) that had their timestamp set to `0000-00-00 00:00:00` (which the website doesn't like) instead of `null` (which the website handles just fine).

I'll make a small code change to prevent this when the EXIF data of the photo contains an invalid date (which was the case here) and have already manually changed all breaking photos to have the correct `null` values. All previously erroring albus should now be visible again. :)
